In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import cv2

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
import os

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))
np.set_printoptions(threshold = None, linewidth = 200)

print(tf.__version__)
print(keras.__version__)

tf.enable_eager_execution()

# sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

1.13.1
2.2.4-tf
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 15720272316751063100
]


In [12]:
num_images = 98
image = np.zeros((num_images, 720, 1280, 3))
for i in range(num_images):
    image[i, :, :, :] = cv2.imread("highway-cctv-footage-images/input_images/img_{}.jpg".format(str(i)), cv2.IMREAD_UNCHANGED)



[[[[ 27.  26.  30.]
   [ 34.  33.  37.]
   [ 48.  47.  51.]
   ...
   [ 67.  70.  75.]
   [ 40.  43.  48.]
   [ 21.  24.  29.]]

  [[ 47.  46.  50.]
   [ 53.  52.  56.]
   [ 67.  66.  70.]
   ...
   [106. 109. 114.]
   [ 77.  80.  85.]
   [ 58.  61.  66.]]

  [[ 48.  47.  51.]
   [ 54.  53.  57.]
   [ 68.  67.  71.]
   ...
   [109. 112. 117.]
   [ 82.  85.  90.]
   [ 64.  67.  72.]]

  ...

  [[ 74.  70.  76.]
   [103.  99. 105.]
   [124. 120. 126.]
   ...
   [114. 116. 124.]
   [ 86.  88.  96.]
   [ 65.  67.  75.]]

  [[ 69.  65.  71.]
   [ 96.  92.  98.]
   [114. 110. 116.]
   ...
   [ 94.  96. 104.]
   [ 64.  66.  74.]
   [ 46.  48.  56.]]

  [[ 32.  28.  34.]
   [ 57.  53.  59.]
   [ 74.  70.  76.]
   ...
   [ 72.  74.  82.]
   [ 42.  44.  52.]
   [ 23.  25.  33.]]]


 [[[ 29.  28.  32.]
   [ 39.  38.  42.]
   [ 52.  51.  55.]
   ...
   [ 70.  73.  78.]
   [ 43.  46.  51.]
   [ 25.  28.  33.]]

  [[ 47.  46.  50.]
   [ 58.  57.  61.]
   [ 71.  70.  74.]
   ...
   [109. 112. 117.]
 