In [1]:
%matplotlib inline

import numpy as np
from numpy import linalg as nla
import scipy as sp
from scipy import linalg as sla
import SHFunctions as shf
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pprint import pprint
from time import time
import os

from jupyterthemes import jtplot
jtplot.style(theme='solarizedl')

from IPython.core.display import display, HTML
np.set_printoptions(linewidth = 270)

In [2]:
# A, S = shf.MakeOneSingA(5, 8, delta = .00000)
# S = np.real(S)


# A = np.load('200121_Coefficients.npy')

In [3]:
X1s = []
# eps = np.linspace(0, 1, 10001)
eps = np.linspace(.9, .9, 1)
for i, e in zip(range(len(eps)), eps):
    A = shf.MakeGenSingA(5, 2, delta = e)
    S = shf.NewtonPoly(A)
    A0 = np.copy(A)
    A0[0,:,:] -= e*S['sol']
    A0[1,:,:] += e*np.eye(A.shape[1])
#     A0[0,:,:] -= e*S
#     A0[1,:,:] += e*np.eye(A.shape[1])
    Ss = shf.NewtonPoly(A0)
    try:
        X1s.append(Ss['Xs'][1])
    except:
        pass

In [7]:
for X1 in X1s:
#     print('{}'.format(np.all(X1 >= 0)), end=' ')
    print(X1 >= 0, end=' ')

[[False  True  True  True  True]
 [False False  True  True  True]
 [ True  True False  True  True]
 [ True  True  True False  True]
 [ True  True False  True False]] 

In [11]:
for X in S['Xs']:
    print(X)
print('========================')
for X in Ss['Xs']:
    print(X)
print(S['Xs'][-1] - Ss['Xs'][-1])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0.00027004 0.00501381 0.00592433 0.01163825 0.01163633]
 [0.00325468 0.00012953 0.00928134 0.00796952 0.01384769]
 [0.00911629 0.00223149 0.00028095 0.0064971  0.01635694]
 [0.00773186 0.00305214 0.01668523 0.00037154 0.00664199]
 [0.01312762 0.00199672 0.002288   0.0166657  0.00040473]]
[[0.0005861  0.00509394 0.00619924 0.01193112 0.01190232]
 [0.00358416 0.00022292 0.00948355 0.00830893 0.01411316]
 [0.00939933 0.00233396 0.00051445 0.0068944  0.01657056]
 [0.00799659 0.00314679 0.01681029 0.00071404 0.00704502]
 [0.01331415 0.00211922 0.00265185 0.01688634 0.00074116]]
[[0.00058644 0.00509407 0.00619955 0.01193152 0.01190271]
 [0.0035845  0.00022304 0.00948385 0.00830933 0.01411356]
 [0.00939968 0.00233409 0.00051475 0.00689481 0.01657096]
 [0.00799692 0.00314691 0.01681061 0.00071442 0.00704543]
 [0.01331448 0.00211935 0.00265217 0.01688674 0.00074154]]
[[0.00058644 0.00509407 0.00619955 0

In [5]:
import numpy as np
print(np.linspace(0, 1, 10001))

[0.000e+00 1.000e-04 2.000e-04 ... 9.998e-01 9.999e-01 1.000e+00]
