In [1]:
%matplotlib inline

import numpy as np
from numpy import linalg as nla
import scipy as sp
from scipy import linalg as sla
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from pprint import pprint
from time import time
# import SHFunctions as shf
import os

from jupyterthemes import jtplot
jtplot.style(theme='solarizedl')

from IPython.core.display import display, HTML
np.set_printoptions(linewidth = 270)

In [2]:
A = np.array([[0,1,1,1,1],[1,0,1,1,1],[1,1,0,1,1],[1,1,1,0,1],[1,1,1,1,0]])

In [3]:
d, X = nla.eig(A)
print(d)
print(X)

[-1.  4. -1. -1. -1.]
[[-0.89442719  0.4472136   0.19518001  0.15432036  0.09319422]
 [ 0.2236068   0.4472136  -0.53674504  0.73302172 -0.25628411]
 [ 0.2236068   0.4472136   0.76445506  0.04715344 -0.25628411]
 [ 0.2236068   0.4472136  -0.21144502 -0.46724776 -0.41160781]
 [ 0.2236068   0.4472136  -0.21144502 -0.46724776  0.8309818 ]]
